document.write("")
day = new Date()
hr = day.getHours()
if ((hr == 1) || (hr == 2) || (hr == 3) || (hr == 4) || (hr == 5) || (hr == 6) || (hr == 7) || (hr == 8) || (hr == 9) || (hr == 10) || (hr == 11))
document.write("Good Morning! <img src='/images/icon_smile.gif' width='15' height='15' style='padding:0px; margin:0px;' />")
if ((hr == 12) || (hr == 13) || (hr == 14) || (hr == 15) || (hr == 16) || (hr == 17))
document.write("Good Afternoon! <img src='/images/icon_biggrin.gif' width='15' height='15' style='padding:0px; margin:0px;' />")
if ((hr == 18) || (hr == 19) || (hr == 20) || (hr == 21) || (hr == 22) || (hr == 23) || (hr == 0))
document.write("Good Evening! <img src='/images/icon_cheesygrin.gif' width='15' height='15' style='padding:0px; margin:0px;' />")
document.write("")